#!/usr/bin/env zsh

up() {
    go_up=${1:-"1"}
    cd_arg="$(python3 -c "print('../' * $go_up)")"
    cd "$cd_arg"
}

exists() {
    type "$1" > /dev/null 2>&1
}

mkcd() {
    mkdir "$@" && cd "$_"
}

# Creates a Python package with an empty __init__.py file
mkpypkg() {
    mkdir "$@" && touch "$_/__init__.py"
}

syncwatch() {
    watch -n0.5 grep -e Dirty: -e Writeback: /proc/meminfo
}