#!/usr/bin/env zsh

# This file contains commands that should be set _prior_ to oh-my-zsh being loaded. In general
# they are commands that set omz config values and plugin lists. It also does some basic config
# for the $PATH and $MANPATH.

export ZSH_DISABLE_COMPFIX="true"
export ZSH="$ZDOTDIR/.oh-my-zsh"

bindkey -v

# oh-my-zsh settings
ZSH_THEME="agnoster"
CASE_SENSITIVE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Plugins
plugins=(sudo zsh-syntax-highlighting virtualenv direnv)

# User configuration
path=("$HOME/.local/bin" $path)
manpath+=("$HOME/.local/share/man" "/usr/local/share/man")

# Ruby Gems
if which ruby &> /dev/null; then
  export GEM_HOME="$(ruby -e "puts Gem.user_dir")"
  path=("$(ruby -e 'puts Gem.user_dir')/bin" $path)
fi

export GPG_TTY="$(tty)"


