#!/usr/bin/env zsh

# Set the XDG directories explicitly (even though these are the default values)

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
