#!/usr/bin/env zsh

up() {
    go_up=${1:-"1"}
    cd_arg=""

    until [ "$go_up" -eq 0 ]; do
        cd_arg="../${cd_arg}"
        go_up=$((go_up - 1))
    done
    cd "$cd_arg"
}

exists() {
    type "$1" > /dev/null 2>&1
}

mkcd() {
    mkdir "$@" && cd "$_"
}

# Creates a Python package with an empty __init__.py file
mkpypkg() {
    mkdir "$@" && touch "$_/__init__.py"
}

syncwatch() {
    watch -n0.5 grep -e Dirty: -e Writeback: /proc/meminfo
}
