source /etc/profile
source "$ZDOTDIR/zsh"
source "$ZDOTDIR/pre-ohmyzsh"
source "$ZDOTDIR/loadtools"
source "$ZSH/oh-my-zsh.sh"
source "$ZDOTDIR/wslconfig"
source "$ZDOTDIR/functions"
source "$ZDOTDIR/aliases"
source "$ZDOTDIR/colors"
source "$ZDOTDIR/wslfixes"
source "$ZDOTDIR/asciinema"
source "$ZDOTDIR/sway"

if [ -f "$ZDOTDIR/local-settings" ]; then
  source "$ZDOTDIR/local-settings"
fi
