---
# ASDF
- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.14.1

# Node configs
- name: Set npm global config
  ini_file:
    path: ~/.npmrc
    section: null
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: fund
      value: "false"
    - option: init-author-name
      value: "{{ me.name }}"
    - option: init-author-email
      value: "{{ me.email }}"
