#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
colorprofile=$HOME/.colorprofile.icc
fehbgscript=$HOME/.fehbg

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi
if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


if [ -d /etc/X11/Xsession.d ] ; then
 for f in /etc/X11/Xsession.d/* ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ -f "$colorprofile" ]; then
    xcalib -d :0 "${colorprofile}"
fi

if [ -f "$fehbgscript" ]; then
    eval "$fehbgscript"
fi

#xrandr --dpi 144
#numlockx on &
exec i3
