---
# tasks file for common
- name: Create local clone
  git:
    repo: "https://github.com/laurelmay/dotfiles"
    dest: "{{ user_local_checkout_dir }}"
  when: local_only is not defined
- name: Create necessary directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ user_config_dir }}'
    - '{{ user_local_dir }}'
    - '{{ user_bin_dir }}'
    - '{{ user_share_dir }}'
    - '{{ user_cache_dir }}'
